### ISSUE TITLE
esdoc instead of jsdoc?

### ISSUE THREAD

**Issue by silkentrance** [christophehurpeau/springbokjs-library#2]
I had a look at esdoc and it seems to be much more suited for babel/es6. How about integrating that instead of jsdoc?

**Comment by christophehurpeau** [comment]
I tried it quickly today, and I've found two problems:
getters/setters are not displayed as properties, but as separated members
there are some problems with jsdoc tags, including the optionnal parameters like `@param {number} [index = -1]`

**Comment by silkentrance** [comment]
Yeah, it still has some problems. Perhaps issuing the probs you found will help?

**Comment by christophehurpeau** [comment]
Opened https://github.com/esdoc/esdoc/issues/108 and https://github.com/esdoc/esdoc/issues/109

**Comment by christophehurpeau** [comment]
Did you test version 11 ?
What do you think about esdoc ?

**Comment by silkentrance** [comment]
@christophehurpeau To be honest, I tried out your fine suite of scripts / Makefiles but since moved on to my own version. As for esdoc, I am using it right now to build the public/dev api docs for my projects, along with wintersmith for building the static sites.

**Comment by christophehurpeau** [comment]
Thanks for your feedback :)
